services:
  app:
    build:
      context: .
      dockerfile: docker-dev/Dockerfile
      args:
        UID: ${UID}
        GID: ${GID}
    container_name: raminte-app
    volumes:
      - .:/var/www/html
      - ${HOME}/mainData/data:/mainData/data
    networks:
      - raminte-net

  nginx:
    image: nginx:alpine
    container_name: raminte-nginx
    ports:
      - "9094:80"
    volumes:
      - .:/var/www/html
      - ./docker-dev/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - raminte-net

networks:
  raminte-net:
    external: true
    name: bisnis-net