version: "3.8"

services:
    app:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        container_name: laravel-app
        volumes:
            - .:/var/www/html
        working_dir: /var/www/html
        depends_on:
            - mysql
        networks:
            - laravel

    nginx:
        image: nginx:alpine
        container_name: laravel-nginx
        ports:
            - "8000:80"
        volumes:
            - .:/var/www/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - laravel

    mysql:
        image: mariadb:11
        container_name: laravel-mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: laravel
            MYSQL_USER: laravel
            MYSQL_PASSWORD: laravel
        volumes:
            - mysql_data:/var/lib/mysql
        ports:
            - "3306:3306"
        networks:
            - laravel

    node:
        image: node:20
        container_name: laravel-node
        working_dir: /var/www/html
        volumes:
            - .:/var/www/html
        command: sh -c "npm install && npm run build"
        networks:
            - laravel

volumes:
    mysql_data:

networks:
    laravel:
